### PR TITLE
Fix travis builds

### PR DESCRIPTION
**Pull request by sionide21**
See https://github.com/travis-ci/travis-ci/issues/3531
and https://github.com/bundler/bundler/issues/3558

### CODE REVIEW

**Comment by sionide21** [comment]
The ruby 2.3 failures are legit, not a travis issue. We don't have ruby 2.3 support at the moment.

**Comment by robforman** [comment]
:+1:

**Comment by robforman** [comment]
What is different with ruby 2.3? The socket libraries?

**Comment by sionide21** [comment]
I haven't investigated much yet, but it appears the method signatures for the stubbed `*_nonblock` methods have changed

**Pull request merged**
